ci workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -140,9 +140,6 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         if: needs.do-test-azure.outputs.do-test == 'true'
-      # TODO: Delete this, fail the job
-      - run: exit 1
-        if: needs.do-test-azure.outputs.do-test == 'true'
       - uses: actions/setup-node@v4
         if: needs.do-test-azure.outputs.do-test == 'true'
         with:
@@ -205,6 +202,9 @@ jobs:
               echo "complete-node-20=false" >> "$GITHUB_OUTPUT"
             fi
           fi
+      # TODO: Delete this, fail the job
+      - run: exit 1
+        if: needs.do-test-azure.outputs.do-test == 'true'
     outputs:
       complete-node-18: ${{ steps.complete.outputs.complete-node-18 }}
       complete-node-20: ${{ steps.complete.outputs.complete-node-20 }}
